[package]
name = "shadow-track"
version = "0.3.0"
edition = "2021"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
rand = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
rfd = "0.15.3"